server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: sharqmotors
          uri: lb://sharqmotors
          predicates:
            - Path=/sharq/**
        - id: tasbackend
          uri: lb://tasbackend
          predicates:
            - Path=/api/**,/custom/**,/login/**

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

